export type BodyPart =
  | 'chest'
  | 'lats'
  | 'upper_back'
  | 'shoulders'
  | 'biceps'
  | 'triceps'
  | 'core'
  | 'quads'
  | 'hamstrings'
  | 'glutes'
  | 'calves'
  | 'full_body';

export interface ExerciseCatalogItem {
  id: string;
  label: string;
  aliases: string[];
  bodyPart: BodyPart;
  defaultTempo: {
    eccentric: number;
    pause: number;
    concentric: number;
  };
  defaultRestSeconds: number;
  cue: string;
}

export const exerciseCatalog: ExerciseCatalogItem[] = [
  {
    id: 'lat-pulldown',
    label: 'Lat Pulldown',
    aliases: ['lat pulldown', 'lat pull down', 'lat pull town', 'pulldown', 'pull down'],
    bodyPart: 'lats',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Keep the chest tall and drive the elbows down instead of yanking with the hands.',
  },
  {
    id: 'assisted-pull-up',
    label: 'Assisted Pull-Up',
    aliases: ['assisted pull up', 'assisted chin up'],
    bodyPart: 'lats',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Finish with the elbows tucked and control the full lowering phase.',
  },
  {
    id: 'pull-up',
    label: 'Pull-Up',
    aliases: ['pull up', 'chin up'],
    bodyPart: 'lats',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 105,
    cue: 'Start from a dead hang and avoid craning the neck over the bar.',
  },
  {
    id: 'seated-cable-row',
    label: 'Seated Cable Row',
    aliases: ['seated cable row', 'cable row', 'seated row', 'machine row'],
    bodyPart: 'upper_back',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Squeeze at the ribcage and own the return instead of dropping the handle.',
  },
  {
    id: 'chest-supported-row',
    label: 'Chest-Supported Row',
    aliases: ['chest supported row', 'supported row'],
    bodyPart: 'upper_back',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Keep the chest glued to the pad and pull through the elbows.',
  },
  {
    id: 'single-arm-dumbbell-row',
    label: 'Single-Arm Dumbbell Row',
    aliases: ['single arm row', 'dumbbell row', 'one arm row'],
    bodyPart: 'upper_back',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Brace hard and row toward the hip instead of shrugging up.',
  },
  {
    id: 'face-pull',
    label: 'Face Pull',
    aliases: ['face pull'],
    bodyPart: 'shoulders',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Pull to forehead height and rotate cleanly through the end range.',
  },
  {
    id: 'bench-press',
    label: 'Bench Press',
    aliases: ['bench press', 'bench'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 120,
    cue: 'Lower to the same touchpoint and keep leg drive on the press.',
  },
  {
    id: 'incline-bench-press',
    label: 'Incline Bench Press',
    aliases: ['incline bench press', 'incline bench'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 105,
    cue: 'Keep the upper back tight and press slightly back over the shoulders.',
  },
  {
    id: 'incline-dumbbell-press',
    label: 'Incline Dumbbell Press',
    aliases: ['incline dumbbell press', 'incline press', 'incline dumbbell bench'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Lower evenly and avoid letting one elbow outrun the other.',
  },
  {
    id: 'dumbbell-press',
    label: 'Dumbbell Press',
    aliases: ['dumbbell press', 'flat dumbbell press'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Keep the wrists stacked and finish each rep with both bells level.',
  },
  {
    id: 'chest-press-machine',
    label: 'Chest Press Machine',
    aliases: ['chest press machine', 'machine press', 'chest press'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Drive through the mid palm and keep the shoulders pinned back.',
  },
  {
    id: 'pec-deck',
    label: 'Pec Deck',
    aliases: ['pec deck', 'pec fly', 'machine fly'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Bring the elbows together under control and resist the stretch on the return.',
  },
  {
    id: 'push-up',
    label: 'Push-Up',
    aliases: ['push up', 'pushup'],
    bodyPart: 'chest',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Keep the body rigid and touch the same depth every rep.',
  },
  {
    id: 'overhead-press',
    label: 'Overhead Press',
    aliases: ['overhead press', 'shoulder press', 'military press'],
    bodyPart: 'shoulders',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 105,
    cue: 'Stack the wrist over the elbow and finish with the ribs down.',
  },
  {
    id: 'dumbbell-shoulder-press',
    label: 'Dumbbell Shoulder Press',
    aliases: ['dumbbell shoulder press', 'dumbbell press shoulder'],
    bodyPart: 'shoulders',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Lower evenly and keep the forearms vertical through the bottom.',
  },
  {
    id: 'arnold-press',
    label: 'Arnold Press',
    aliases: ['arnold press'],
    bodyPart: 'shoulders',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Rotate smoothly and keep the shrug out of the top half of the lift.',
  },
  {
    id: 'lateral-raise',
    label: 'Lateral Raise',
    aliases: ['lateral raise', 'side raise'],
    bodyPart: 'shoulders',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Float to shoulder height and keep tension all the way down.',
  },
  {
    id: 'rear-delt-fly',
    label: 'Rear Delt Fly',
    aliases: ['rear delt fly', 'reverse fly', 'rear delt raise'],
    bodyPart: 'shoulders',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Lead wide through the elbows and keep the neck relaxed.',
  },
  {
    id: 'bicep-curl',
    label: 'Bicep Curl',
    aliases: ['bicep curl', 'curl', 'barbell curl', 'dumbbell curl'],
    bodyPart: 'biceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Let the biceps control the lowering phase instead of swinging into the next rep.',
  },
  {
    id: 'ez-bar-curl',
    label: 'EZ-Bar Curl',
    aliases: ['ez bar curl', 'ez curl'],
    bodyPart: 'biceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Keep the elbows quiet and stop the torso from helping the first rep.',
  },
  {
    id: 'hammer-curl',
    label: 'Hammer Curl',
    aliases: ['hammer curl'],
    bodyPart: 'biceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Stay tall and keep the thumbs traveling straight up, not inward.',
  },
  {
    id: 'cable-curl',
    label: 'Cable Curl',
    aliases: ['cable curl'],
    bodyPart: 'biceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Use the cable tension and keep the elbow angle honest at the bottom.',
  },
  {
    id: 'preacher-curl',
    label: 'Preacher Curl',
    aliases: ['preacher curl'],
    bodyPart: 'biceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Control the stretch and avoid popping off the bottom pad position.',
  },
  {
    id: 'tricep-pushdown',
    label: 'Tricep Pushdown',
    aliases: ['tricep pushdown', 'tricep pressdown', 'pushdown', 'pressdown'],
    bodyPart: 'triceps',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Pin the elbows and finish by fully straightening without leaning on the stack.',
  },
  {
    id: 'overhead-tricep-extension',
    label: 'Overhead Tricep Extension',
    aliases: ['overhead tricep extension', 'overhead extension', 'tricep extension'],
    bodyPart: 'triceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Let the elbows point forward and stretch long without flaring wide.',
  },
  {
    id: 'skull-crusher',
    label: 'Skull Crusher',
    aliases: ['skull crusher', 'lying tricep extension'],
    bodyPart: 'triceps',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Lower behind the forehead path and keep the upper arm fixed.',
  },
  {
    id: 'barbell-squat',
    label: 'Barbell Squat',
    aliases: ['squat', 'back squat', 'barbell squat'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 120,
    cue: 'Own the descent, stay braced at the bottom, then drive up with intent.',
  },
  {
    id: 'front-squat',
    label: 'Front Squat',
    aliases: ['front squat'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 120,
    cue: 'Keep the chest proud and elbows high through the hardest part of the ascent.',
  },
  {
    id: 'hack-squat',
    label: 'Hack Squat',
    aliases: ['hack squat'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 105,
    cue: 'Use full depth you can own and avoid bouncing through the machine stops.',
  },
  {
    id: 'leg-press',
    label: 'Leg Press',
    aliases: ['leg press'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 120,
    cue: 'Use full depth you can own and avoid bouncing out of the bottom.',
  },
  {
    id: 'leg-extension',
    label: 'Leg Extension',
    aliases: ['leg extension', 'quad extension'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Squeeze the top cleanly and resist the drop back to the bottom.',
  },
  {
    id: 'split-squat',
    label: 'Split Squat',
    aliases: ['split squat'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Stay balanced front to back and let the front leg do the work.',
  },
  {
    id: 'bulgarian-split-squat',
    label: 'Bulgarian Split Squat',
    aliases: ['bulgarian split squat', 'rear foot elevated split squat'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Sink straight down with a stable front foot and finish through the whole foot.',
  },
  {
    id: 'walking-lunge',
    label: 'Walking Lunge',
    aliases: ['walking lunge', 'lunge'],
    bodyPart: 'quads',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Stay tall through the torso and make each step deliberate instead of rushing forward.',
  },
  {
    id: 'romanian-deadlift',
    label: 'Romanian Deadlift',
    aliases: ['romanian deadlift', 'rdl', 'romanian dead lift'],
    bodyPart: 'hamstrings',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 105,
    cue: 'Push the hips back and feel the hamstrings load before standing tall again.',
  },
  {
    id: 'deadlift',
    label: 'Deadlift',
    aliases: ['deadlift', 'dead lift'],
    bodyPart: 'full_body',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 150,
    cue: 'Reset the brace each rep and keep the bar close instead of rushing the floor.',
  },
  {
    id: 'stiff-leg-deadlift',
    label: 'Stiff-Leg Deadlift',
    aliases: ['stiff leg deadlift', 'stiff leg dead lift'],
    bodyPart: 'hamstrings',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 105,
    cue: 'Own the stretch and keep the knees soft without turning it into an RDL shrug.',
  },
  {
    id: 'hip-thrust',
    label: 'Hip Thrust',
    aliases: ['hip thrust'],
    bodyPart: 'glutes',
    defaultTempo: { eccentric: 2, pause: 2, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Lock out by squeezing the glutes, not by overextending the lower back.',
  },
  {
    id: 'glute-bridge',
    label: 'Glute Bridge',
    aliases: ['glute bridge'],
    bodyPart: 'glutes',
    defaultTempo: { eccentric: 2, pause: 2, concentric: 1 },
    defaultRestSeconds: 75,
    cue: 'Keep the ribs down and finish with a hard glute squeeze at the top.',
  },
  {
    id: 'hamstring-curl',
    label: 'Hamstring Curl',
    aliases: ['hamstring curl', 'leg curl'],
    bodyPart: 'hamstrings',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Curl smoothly and resist the stack all the way back to the stretch.',
  },
  {
    id: 'good-morning',
    label: 'Good Morning',
    aliases: ['good morning'],
    bodyPart: 'hamstrings',
    defaultTempo: { eccentric: 3, pause: 1, concentric: 1 },
    defaultRestSeconds: 90,
    cue: 'Hinge from the hips with a fixed brace and stop before the spine gives up position.',
  },
  {
    id: 'standing-calf-raise',
    label: 'Standing Calf Raise',
    aliases: ['standing calf raise', 'calf raise'],
    bodyPart: 'calves',
    defaultTempo: { eccentric: 2, pause: 2, concentric: 1 },
    defaultRestSeconds: 45,
    cue: 'Pause hard at the stretched bottom and finish tall through the big toe.',
  },
  {
    id: 'seated-calf-raise',
    label: 'Seated Calf Raise',
    aliases: ['seated calf raise'],
    bodyPart: 'calves',
    defaultTempo: { eccentric: 2, pause: 2, concentric: 1 },
    defaultRestSeconds: 45,
    cue: 'Let the soleus work by controlling the stretch and holding the top.',
  },
  {
    id: 'cable-crunch',
    label: 'Cable Crunch',
    aliases: ['cable crunch'],
    bodyPart: 'core',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 45,
    cue: 'Curl the ribcage down instead of just hinging the hips backward.',
  },
  {
    id: 'hanging-leg-raise',
    label: 'Hanging Leg Raise',
    aliases: ['hanging leg raise', 'leg raise'],
    bodyPart: 'core',
    defaultTempo: { eccentric: 2, pause: 1, concentric: 1 },
    defaultRestSeconds: 45,
    cue: 'Tuck the pelvis under and control the swing before starting the next rep.',
  },
  {
    id: 'plank',
    label: 'Plank',
    aliases: ['plank'],
    bodyPart: 'core',
    defaultTempo: { eccentric: 1, pause: 30, concentric: 1 },
    defaultRestSeconds: 45,
    cue: 'Brace hard and keep the ribs tucked instead of sagging through the low back.',
  },
  {
    id: 'farmer-carry',
    label: 'Farmer Carry',
    aliases: ['farmer carry', 'farmers carry'],
    bodyPart: 'full_body',
    defaultTempo: { eccentric: 1, pause: 0, concentric: 1 },
    defaultRestSeconds: 60,
    cue: 'Walk tall with quiet steps and keep the handles pinned by your sides.',
  },
];
